server:
  port: 8585



logging:
  level:
    org.springframework: ERROR
    com.alfa: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"

giphy:
  api:
    apiKey: HWtloR33jm7x8XgU1fEZyx2a2Oyu8LhE
    randomGifUrl: api.giphy.com/v1/gifs/random

openexchangerate:
  api:
    url: https://openexchangerates.org/api/
    appId: d08482c18e014da68d6b35049ca50cd1
    base: USD # default. Other option are only for enterprise clients