server:
  port: 8585

giphy:
  api:
    apiKey: HWtloR33jm7x8XgU1fEZyx2a2Oyu8LhE
    randomGifUrl: api.giphy.com/v1/gifs/random

openexchangerate:
  api:
    url: https://openexchangerates.org/api/
    appId: d08482c18e014da68d6b35049ca50cd1
    base: USD # default. Other option are only for enterprise clients